### ISSUE TITLE
No tags for files in group folders

### ISSUE THREAD

**Issue by girstenbrei** [nextcloud/files_automatedtagging#46]
### Steps to reproduce
1. Nextcloud 12.0.4 or 12.0.5
2. Files automated tagging 1.2.2
3. Group Folders 1.2.0

### Expected behaviour
Upload a file via webinterface or desktop client to the server to any folder -> file gets auto tagged

### Actual behaviour
No tags in group folders.

The file gets tagged when uploaded to a private (or shared) user folder, just not if uploaded to a group folder.

Also see [here](https://help.nextcloud.com/t/files-automated-tagging-not-working-on-group-folders/26774), someone else with the same problem.

## Server configuration detail

**Operating system:** Linux 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 10.0.33

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.1.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - caniupdate: 0.1.2
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.2.0
 - dav: 1.3.0
 - deck: 0.3.0
 - defaultgroup: 0.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_automatedtagging: 1.2.2
 - files_clipboard: 0.7.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - polls: 0.8.1
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.40
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.6
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - encryption
 - files_external
 - impersonate
 - notes
 - registration
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "oczislxvuny1",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.action-online.de"
    ],
    "datadirectory": "\/tank\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/cloud.action-online.de",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "admin",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "cloud.action-online.de",
    "mail_smtpsecure": "tls",
    "mail_smtphost": "mail.agenturserver.de",
    "mail_smtpport": "25",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by lazylionca** [comment]
I'll seconds this issue. Nextcloud 12.0.5. No tagging is happening in group folders.

**Comment by PhantomPhreak** [comment]
I have the same issue with a group folders. Nextcloud 13.0.2
There are also issue in groupfolders project: https://github.com/nextcloud/groupfolders/issues/106

**Comment by Vladikamira** [comment]
the same problem as @PhantomPhreak has

**Comment by igloo777** [comment]
+1 to comment of @PhantomPhreak and @girstenbrei - no tagging in Group Folders.

**Comment by Franjovi** [comment]
Problem is still existing unfortunately.

**Comment by Oz246** [comment]
Still no solution?

**Comment by neeral85** [comment]
same issue with 14.01

**Comment by maghog** [comment]
+1

**Comment by Vince4Git** [comment]
+1

**Comment by Oz246** [comment]
Still no solution?

**Comment by Subnum12** [comment]
+1

**Comment by ducemollari** [comment]
+1

**Comment by Henry-White** [comment]
+1

**Comment by nickvergessen** [comment]
This was fixed with #71

**Comment by DecaTec** [comment]
@nickvergessen Unfortunately this still doesn't work with 1.6.0 of the app (and NC 16), see here: https://github.com/nextcloud/files_automatedtagging/issues/76

My current setup is with PostgreSQL, but I also tested it with a fresh install of NC 16 with MariaDB.

Can anyone confirm that this is working with 1.6.0 od the app and NC 16?

**Comment by jorgv** [comment]
I have the same problem with 16.0.3 still not working, both #76 and #46 are closed? is this bug still on the roadmap?
